Assignment12/src/objects/Archive_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <label>Developer Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Filter__c</fullName>
        <label>Filter</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Archive Config</label>
    <pluralLabel>Archive Configs</pluralLabel>
</CustomObject>

Assignment12/src/classes/ScheduleDeleteOldRecordsBatch.cls
global without sharing class ScheduleDeleteOldRecordsBatch implements Schedulable{
    private String obj;
    private String fieldNameForQuery ='';
	public static Integer count = 0;
    global void execute(SchedulableContext sc){
        List<SObject> metadata = [SELECT Developer_Name__c,Duration__c,Filter__c FROM Archive_Config__mdt];
		System.debug(metadata);
        for(SObject  eachObj : metadata){
            fieldNameForQuery = '';
            Decimal duration = (Decimal)eachObj.get('Duration__c');
            String developerName = (String)eachObj.get('Developer_Name__c');
            String filter = (String)eachObj.get('Filter__c');
            Schema.SObjectType SObjectInstance = ((SObject)Type.forName(developerName).newInstance()).getSObjectType();
            Map<String, Schema.SObjectField> fieldMapForDeveloperName = SObjectInstance.getDescribe().fields.getMap();
            for (Schema.SObjectField eachObjField : fieldMapForDeveloperName.values()) {
                Schema.DescribeFieldResult fieldResult = eachObjField.getDescribe();
                if(fieldResult.isAccessible()){
                    fieldNameForQuery += fieldResult.getName()+ ', ';
                }
            }
            fieldNameForQuery= fieldNameForQuery.substring(0,fieldNameForQuery.lastIndexOf(', '));
            String query = 'SELECT ' +fieldNameForQuery+ ' FROM ' +developerName+ 
                           ' WHERE '+filter+ ' AND CreatedDate >= LAST_N_DAYS:'+ duration;
			System.debug(query);
			Database.executeBatch(new DeleteOldRecordsBatch(query));
			count++;
        } 
    }
}