Assignment5/src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Session_Name__c</fullName>
        <description>Master - detailed relationship to attendee , where training session is the parent and attendee is child .</description>
        <label>Training Session Name</label>
        <referenceTo>Training_Session__c</referenceTo>
        <relationshipLabel>Attendees (Training Session Name)</relationshipLabel>
        <relationshipName>Attendees1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Assignment5/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Number_of_Sessions__c</fullName>
        <description>Number of training sessions attendee is enrolled .</description>
        <inlineHelpText>Display number of training sessions attendee is enrolled.</inlineHelpText>
        <label>Number of Sessions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Assignment5/src/objects/Training_Session__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Sessions__c</fullName>
        <description>How many sessions is going to to happen .</description>
        <inlineHelpText>Give the number of sessions going to happen.</inlineHelpText>
        <label>Number of Sessions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training Session</label>
    <nameField>
        <label>Training Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Assignment7/src/classes/AttendeeTriggerHelperTest.cls
/** 
* Purpose          :   Test Class of HelperAttendeeTrigger.
* 
* Created by       :   Priyank Kumawat
* 
* Created Date     :   12-12-2024
* 
* Revision Logs    :   V_1.0 - Created
**/
@isTest
private class AttendeeTriggerHelperTest {
    /**
    * Method Name  :   testAfterInsert
    * 
    * Created by   :   Priyank Kumawat
    * 
    * Purpose      :   This test ensure the logic correctly updates the Number_of_Sessions__c field based on 
    *                  associated Attendee__c records on every Possible insert.
    *
    * return       :   void
    *
    * param        :   null
    **/
    @isTest
    static void testAfterInsert() {
        Contact contact1 = new Contact(FirstName = 'Priyank', LastName = 'Kumawat');
        Contact contact2 = new Contact(FirstName = 'Sajal', LastName = 'Mittal');
        insert new List<Contact>{contact1, contact2};

        Training_Session__c trainingSession1 = new Training_Session__c(Name = 'Session 1');
        Training_Session__c trainingSession2 = new Training_Session__c(Name = 'Session 2');
        insert new List<Training_Session__c>{trainingSession1, trainingSession2};

        Attendee__c attendee1 = new Attendee__c(Contact__c = contact1.Id, Training_Session_Name__c = trainingSession1.id);
        Attendee__c attendee2 = new Attendee__c(Contact__c = contact1.Id, Training_Session_Name__c = trainingSession2.id);
        Attendee__c attendee3 = new Attendee__c(Contact__c = contact2.Id, Training_Session_Name__c = trainingSession1.id);
        insert new List<Attendee__c>{attendee1, attendee2, attendee3};

        contact1 = [SELECT Id, Number_of_Sessions__c FROM Contact WHERE Id = :contact1.Id];
        contact2 = [SELECT Id, Number_of_Sessions__c FROM Contact WHERE Id = :contact2.Id];

        System.assertEquals(2, contact1.Number_of_Sessions__c, 'Contact 1 should have 2 sessions');
        System.assertEquals(1, contact2.Number_of_Sessions__c, 'Contact 2 should have 1 session');
    }
    /**
    * Method Name  :   testAfterUpdate
    * 
    * Created by   :   Priyank Kumawat
    * 
    * Purpose      :   This test ensure the logic correctly updates the Number_of_Sessions__c field based on 
    *                  associated Attendee__c records on every Possible updates.
    *
    * return       :   void
    *
    * param        :   null
    **/
    @isTest
    static void testAfterUpdate() {
        Contact contact1 = new Contact(FirstName = 'Priyank', LastName = 'Kumawat');
        Contact contact2 = new Contact(FirstName = 'Sajal', LastName = 'Mittal');
        insert new List<Contact>{contact1, contact2};
            
        Training_Session__c trainingSession1 = new Training_Session__c(Name = 'Session 1');
        Training_Session__c trainingSession2 = new Training_Session__c(Name = 'Session 2');
		Training_Session__c trainingSession3 = new Training_Session__c(Name = 'Session 3');
        insert new List<Training_Session__c>{trainingSession1, trainingSession2, trainingSession3};
      
        Attendee__c attendee1 = new Attendee__c(Contact__c = contact1.Id, Training_Session_Name__c = trainingSession1.id);
        Attendee__c attendee2 = new Attendee__c(Contact__c = contact1.Id, Training_Session_Name__c = trainingSession2.id);
        Attendee__c attendee3 = new Attendee__c(Contact__c = contact2.Id, Training_Session_Name__c = trainingSession1.id);
        insert new List<Attendee__c>{attendee1, attendee2, attendee3};
        
		attendee1.Contact__c = contact2.Id;
        update attendee1;
        
		contact1 = [SELECT Id, Number_of_Sessions__c FROM Contact WHERE Id = :contact1.Id];
        contact2 = [SELECT Id, Number_of_Sessions__c FROM Contact WHERE Id = :contact2.Id];

        System.assertEquals(1, contact1.Number_of_Sessions__c, 'Contact 1 should have 2 sessions after update');
        System.assertEquals(1, contact2.Number_of_Sessions__c, 'Contact 2 should have 1 session after update');
    }
    /**
    * Method Name  :   testAfterDelete
    * 
    * Created by   :   Priyank Kumawat
    * 
    * Purpose      :   This test ensure the logic correctly updates the Number_of_Sessions__c field based on 
    *                  associated Attendee__c records on every Possible delete.
    *
    * return       :   void
    *
    * param        :   null
    **/
    @isTest
    static void testAfterDelete() {
        Contact contact1 = new Contact(FirstName = 'Priyank', LastName = 'Kumawat');
        Contact contact2 = new Contact(FirstName = 'Sajal', LastName = 'Mittal');
        insert new List<Contact>{contact1, contact2};

        Training_Session__c trainingSession1 = new Training_Session__c(Name = 'Session 1');
        Training_Session__c trainingSession2 = new Training_Session__c(Name = 'Session 2');
        insert new List<Training_Session__c>{trainingSession1, trainingSession2};

        Attendee__c attendee1 = new Attendee__c(Contact__c = contact1.Id, Training_Session_Name__c = trainingSession1.id);
        Attendee__c attendee2 = new Attendee__c(Contact__c = contact1.Id, Training_Session_Name__c = trainingSession2.id);
        Attendee__c attendee3 = new Attendee__c(Contact__c = contact2.Id, Training_Session_Name__c = trainingSession1.id);
        insert new List<Attendee__c>{attendee1, attendee2, attendee3};

        delete attendee2;

        contact1 = [SELECT Id, Number_of_Sessions__c FROM Contact WHERE Id = :contact1.Id];
        contact2 = [SELECT Id, Number_of_Sessions__c FROM Contact WHERE Id = :contact2.Id];

        System.assertEquals(1, contact1.Number_of_Sessions__c, 'Contact 1 should have 1 session after delete');
        System.assertEquals(1, contact2.Number_of_Sessions__c, 'Contact 2 should have 1 session after delete');
		
		delete attendee1;
		contact1 = [SELECT Id, Number_of_Sessions__c FROM Contact WHERE Id = :contact1.Id];
		System.assertEquals(0, contact1.Number_of_Sessions__c, 'Contact 1 should have 0 session after delete');

    }
    /**
    * Method Name  :   testEmptyContactRecords
    * 
    * Created by   :   Priyank Kumawat
    * 
    * Purpose      :   This test ensure the logic correctly updates the Number_of_Sessions__c field based on 
    *                  associated Attendee__c records on empty values.
    *
    * return       :   void
    *
    * param        :   null
    **/
    @isTest
    static void testEmptyContactRecords() {
        Contact contact1 = new Contact(FirstName = 'Priyank', LastName = 'Kumawat');
        insert new List<Contact>{contact1};
		List<Attendee__c> emptyAttendees = new List<Attendee__c>();

        Test.startTest();
        HelperAttendeeTrigger.updateNoOfSessionsOnContact(emptyAttendees, null);
        Test.stopTest();

        contact1 = [SELECT Id, Number_of_Sessions__c FROM Contact WHERE Id = :contact1.Id];
        System.assertEquals(null, contact1.Number_of_Sessions__c, 'Contact should have 0 sessions when there are no attendees');
    } 
}