Assignment5/src/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Session_Name__c</fullName>
        <description>Master - detailed relationship to attendee , where training session is the parent and attendee is child .</description>
        <label>Training Session Name</label>
        <referenceTo>Training_Session__c</referenceTo>
        <relationshipLabel>Attendees (Training Session Name)</relationshipLabel>
        <relationshipName>Attendees1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Assignment5/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Number_of_Sessions__c</fullName>
        <description>Number of training sessions attendee is enrolled .</description>
        <inlineHelpText>Display number of training sessions attendee is enrolled.</inlineHelpText>
        <label>Number of Sessions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Assignment5/src/classes/HelperAttendeeTrigger.cls
/** 
 * Purpose          :   Handler Class of Trigger on Attendee__c object
 * 
 * Created by       :   Priyank Kumawat
 * 
 * Created Date     :   08-12-2024
 * 
 * Rivision Logs    :   V_1.0 - Created
**/
public without sharing class HelperAttendeeTrigger {
    /**
    * Method Name  :   updateNoOfSessionsOnContact
    * 
    * Created by   :   Priyank Kumawat
    * 
    * Purpose      :   Method will update 'No. Of Attended Training Session' field on contact object according to the  
                       number of session that contact is enrolled.
    *
    * return       :   void
    *
    * param        :   List<Attendee__c> newListOfAttendee, Map<Id, Attendee__c> mapOfOldAttendies
    **/
    public static void updateNoOfSessionsOnContact(List<Attendee__c> newListOfAttendee, Map<Id, Attendee__c> mapOfOldAttendies) {
        if( (newListOfAttendee != null && mapOfOldAttendies != null) || (newListOfAttendee != null)){
            Set<Id> setOfIds = new Set<Id>();
            for(Attendee__c att : newListOfAttendee) {
                if(att.Contact__c != null){
                    setOfIds.add(att.Contact__c);
                }
            }
            List<Attendee__c> listOfAttendee = [SELECT Id, Contact__c, Training_Session_Name__c 
                                                FROM Attendee__c  
                                                WHERE Contact__c IN :setOfIds];
            Map<Id, Set<Id>> mapOfContactIdAndTrainingSessions = new Map<Id, Set<Id>>();
            for(Attendee__c att : listOfAttendee) {
                if(att.Contact__c != null){
                        if(!mapOfContactIdAndTrainingSessions.containsKey(att.Contact__c)){
                            mapOfContactIdAndTrainingSessions.put(att.Contact__c, new Set<Id>());
                        }
                    mapOfContactIdAndTrainingSessions.get(att.Contact__c).add(att.Training_Session_Name__c);
                }
            }
            List<Contact> contactsToUpdate = new List<Contact>();
            for (Id contactId : mapOfContactIdAndTrainingSessions.keySet()) {
                 Contact con = new Contact(
                 	Id = contactId, Number_of_Sessions__c = (!mapOfContactIdAndTrainingSessions.get(contactId).isEmpty() 
        			                 ? mapOfContactIdAndTrainingSessions.get(contactId).size() : 0));
		 contactsToUpdate.add(con);
            }
            if (!contactsToUpdate.isEmpty()) {
                update contactsToUpdate;
            }
        }
        if((mapOfOldAttendies != null && newListOfAttendee != null) || (mapOfOldAttendies != null)){
            for(Id AttendeeId : mapOfOldAttendies.keySet()){
                if(mapOfOldAttendies.get(AttendeeId).Contact__c == null){
                    return;
                }
            }
            Set<Id> setOfIds = new Set<Id>();
            for (Attendee__c att : mapOfOldAttendies.values()) {
                if (att.Contact__c != null) {
                    setOfIds.add(att.Contact__c);
                }
            }
            List<Attendee__c> listOfAttendee = [SELECT Id, Contact__c, Training_Session_Name__c 
                                                FROM Attendee__c  
                                                WHERE Contact__c IN :setOfIds];
            List<Contact> contactsToUpdate = new List<Contact>();
            if (listOfAttendee.size()==0) {
				for(Id AttendeeId : mapOfOldAttendies.keySet()){
                    System.debug(AttendeeId);
                    Contact con = new Contact(Id =mapOfOldAttendies.get(AttendeeId).Contact__c, Number_of_Sessions__c = 0.00);
                    System.debug(con);
                    contactsToUpdate.add(con);
                }
            }else{
                Map<Id, Set<Id>> mapOfContactIdAndTrainingSessions = new Map<Id, Set<Id>>();
                for (Attendee__c att : listOfAttendee) {    
                     if (att.Contact__c != null) {
                         if (!mapOfContactIdAndTrainingSessions.containsKey(att.Contact__c)) {
                             mapOfContactIdAndTrainingSessions.put(att.Contact__c, new Set<Id>());
                         }
                         mapOfContactIdAndTrainingSessions.get(att.Contact__c).add(att.Training_Session_Name__c);
                     }
                }
                    for (Id contactId : mapOfContactIdAndTrainingSessions.keySet()) {
                        Set<Id> trainingSessions = mapOfContactIdAndTrainingSessions.get(contactId);
                        for (Attendee__c att : mapOfOldAttendies.values()) {
                            if (att.Contact__c == contactId) {
                                trainingSessions.remove(att.Training_Session_Name__c);
                            }
                        }
                        if (trainingSessions.size() != null) {
                            Contact con = new Contact(Id = contactId, Number_of_Sessions__c = (!trainingSessions.isEmpty() 
        							                               ? trainingSessions.size() : 0));
                            contactsToUpdate.add(con);
                        }
                    }
                } 
            if (!contactsToUpdate.isEmpty()) {
                update contactsToUpdate;
            }
	}
    }
}